eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #give time to service clients to register with eureka.(default 5 minutes)
    #Spring Microservices in Action, Page 161
    wait-time-in-ms-when-sync-empty: 5