-- Database: cmdlicesys_dev

-- DROP DATABASE IF EXISTS licesys_dev;

CREATE DATABASE cmdlicesys_dev
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- command to switch the desired database
\c cmdlicesys_dev

CREATE TABLE public.OWNER (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ID_CARD VARCHAR(12) NOT NULL,
	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64) NOT NULL,
	AGE INT,
	CREATED_BY VARCHAR(256) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	MODIFIED_BY VARCHAR(256),
	MODIFIED_AT TIMESTAMP
);

CREATE UNIQUE INDEX IDX_OWNER_IDCARD ON public.OWNER (ID_CARD);
ALTER TABLE public.OWNER ADD CONSTRAINT UNIQUE_OWNER_IDCARD UNIQUE USING INDEX IDX_OWNER_IDCARD;

CREATE TABLE public.LICENSE (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LICENSE_NUMBER VARCHAR(256) NOT NULL,
	OWNER_ID BIGINT NOT NULL REFERENCES public.OWNER(ID),
	ISSUE_DATE TIMESTAMP NOT NULL,
	EXPIRATION_DATE TIMESTAMP NOT NULL,
	TYPE SMALLINT NOT NULL,
	STATUS SMALLINT NOT NULL,
	CREATED_BY VARCHAR(256) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL,
	MODIFIED_BY VARCHAR(256),
	MODIFIED_AT TIMESTAMP
);

CREATE INDEX IDX_LICENSE_NUMBER ON public.LICENSE(LICENSE_NUMBER);
CREATE UNIQUE INDEX IDX_OWNER_ID_LIC_TYPE ON public.LICENSE(OWNER_ID, TYPE);
ALTER TABLE public.LICENSE ADD CONSTRAINT UNIQUE_OWNERID_LICTYPE UNIQUE USING INDEX IDX_OWNER_ID_LIC_TYPE;
