\c cmdlicesys_dev

INSERT INTO public.OWNER(ID_CARD,FIRST_NAME,LAST_NAME,AGE,CREATED_BY,CREATED_AT)
	VALUES('47928848','SAMMY','YARIN',21,'DATABASE',CURRENT_TIMESTAMP);
INSERT INTO public.OWNER(ID_CARD,FIRST_NAME,LAST_NAME,AGE,CREATED_BY,CREATED_AT)
	VALUES('45682136','SUSAN','SMITH',41,'DATABASE',CURRENT_TIMESTAMP);
INSERT INTO public.OWNER(ID_CARD,FIRST_NAME,LAST_NAME,AGE,CREATED_BY,CREATED_AT)
	VALUES('98756321','FRANK','SINATRA',55,'DATABASE',CURRENT_TIMESTAMP);
