services:
  config-server:
    image: licesys/config-server:0.0.1-SNAPSHOT
    ports:
       - "8074:8074"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      SERVER_PORT_1: 8074
    networks:
      backend:
        aliases:
          - "config-server"

networks:
  backend:
    driver: bridge