services:
  cmd-database:
    image: postgres:16.4
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      #POSTGRES_DB:       "licesys_dev"
    volumes:
        - ./1-init-postgres.sql:/docker-entrypoint-initdb.d/1-init-postgres.sql
        - ./2-data-postgres.sql:/docker-entrypoint-initdb.d/2-data-postgres.sql
        - postgres-data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - "cmd-database"
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  query-database:
    image: mongo:6.0.17
    ports:
      - "27117:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./1-init-mongo.js:/docker-entrypoint-initdb.d/1-init-mongo.js #BIND VOLUME
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb
    networks:
      backend:
        aliases:
          - "query-database"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      backend:
        aliases:
          - "prometheus"

  grafana:
    image: grafana/grafana-oss:11.0.4
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      backend:
        aliases:
          - "grafana"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      backend:
        aliases:
          - "zookeeper"
  #TODO - CREATE TOPICS AND ITS PARTITIONS FROM HERE.
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:  # exposed ports to be accessed by external clients(ex. from local machine)
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # PLAINTEXT://kafka:19092 -> internal port to be accessed by clients inside the same docker network
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,CONNECTIONS_FROM_HOST://localhost:9092,IP_HOST://192.168.1.37:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT,IP_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      backend:
        aliases:
          - "kafka"
    

  # config-server:
  #   image: licesys/config-server:0.0.1-SNAPSHOT
  #   ports:
  #      - "8074:8074"
  #   environment:
  #     ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
  #     SERVER_PORT_1: 8074
  #   networks:
  #     backend:
  #       aliases:
  #         - "config-server"

#NAMED VOLUMES (the default driver storage is 'local')
volumes:
  postgres-data:
  mongodb-data:
  mongodb-log:
  prometheus-data:

networks:
  backend:
    driver: bridge