global:
  scrape_interval: "2s"
  #scrape_timeout: "10s"
  #evaluation_interval: "1m"

scrape_configs:
  - job_name: 'license-command-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.37:8080']
      #- labels:
      #    application: ''

    
    