app:
  title: License Microservice - dev
  
  # DataSource settings: set here your own configurations for the database
spring:
  data:
    mongodb:
      host: localhost
      port: 27117
      database: querylicesys_dev
      username: umongo
      password: pmongo
      
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      security:
        protocol: PLAINTEXT
      group-id: event-group
      auto-offset-reset: latest


